/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as EmprestimosRouteImport } from './routes/emprestimos'
import { Route as GastosFixosRouteImport } from './routes/gastos-fixos'
import { Route as LancamentosRouteImport } from './routes/lancamentos'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const EmprestimosRoute = EmprestimosRouteImport.update({
  id: '/emprestimos',
  path: '/emprestimos',
  getParentRoute: () => rootRouteImport,
} as any)
const GastosFixosRoute = GastosFixosRouteImport.update({
  id: '/gastos-fixos',
  path: '/gastos-fixos',
  getParentRoute: () => rootRouteImport,
} as any)
const LancamentosRoute = LancamentosRouteImport.update({
  id: '/lancamentos',
  path: '/lancamentos',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/emprestimos': typeof EmprestimosRoute
  '/gastos-fixos': typeof GastosFixosRoute
  '/lancamentos': typeof LancamentosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/emprestimos': typeof EmprestimosRoute
  '/gastos-fixos': typeof GastosFixosRoute
  '/lancamentos': typeof LancamentosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/emprestimos': typeof EmprestimosRoute
  '/gastos-fixos': typeof GastosFixosRoute
  '/lancamentos': typeof LancamentosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/dashboard' | '/emprestimos' | '/gastos-fixos' | '/lancamentos'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dashboard' | '/emprestimos' | '/gastos-fixos' | '/lancamentos'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/emprestimos'
    | '/gastos-fixos'
    | '/lancamentos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  EmprestimosRoute: typeof EmprestimosRoute
  GastosFixosRoute: typeof GastosFixosRoute
  LancamentosRoute: typeof LancamentosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emprestimos': {
      id: '/emprestimos'
      path: '/emprestimos'
      fullPath: '/emprestimos'
      preLoaderRoute: typeof EmprestimosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gastos-fixos': {
      id: '/gastos-fixos'
      path: '/gastos-fixos'
      fullPath: '/gastos-fixos'
      preLoaderRoute: typeof GastosFixosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lancamentos': {
      id: '/lancamentos'
      path: '/lancamentos'
      fullPath: '/lancamentos'
      preLoaderRoute: typeof LancamentosRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  EmprestimosRoute: EmprestimosRoute,
  GastosFixosRoute: GastosFixosRoute,
  LancamentosRoute: LancamentosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
